import { BaseNode } from "@nodetool/node-sdk";
import type { NodeClass } from "@nodetool/node-sdk";

function titleFromNodeType(nodeType: string): string {
  const parts = nodeType.split(".");
  return parts[parts.length - 1] ?? nodeType;
}

function makePlaceholderNode(nodeType: string): NodeClass {
  class PlaceholderNode extends BaseNode {
    static readonly nodeType = nodeType;
    static readonly title = titleFromNodeType(nodeType);
    static readonly description = `Placeholder node for ${nodeType}`;

    async process(inputs: Record<string, unknown>): Promise<Record<string, unknown>> {
      if ("output" in inputs) return { output: inputs.output };
      if ("value" in inputs) return { output: inputs.value };
      if ("input_value" in inputs) return { output: inputs.input_value };
      const keys = Object.keys(inputs);
      if (keys.length === 1) return { output: inputs[keys[0]] };
      return { output: inputs };
    }
  }

  return PlaceholderNode as unknown as NodeClass;
}

export const EXTENDED_PLACEHOLDER_NODE_TYPES = [
  "nodetool.agents.Summarizer",
  "nodetool.agents.CreateThread",
  "nodetool.agents.Extractor",
  "nodetool.agents.Classifier",
  "nodetool.agents.Agent",
  "nodetool.agents.ControlAgent",
  "nodetool.agents.ResearchAgent",
  "nodetool.audio.LoadAudioAssets",
  "nodetool.audio.LoadAudioFile",
  "nodetool.audio.LoadAudioFolder",
  "nodetool.audio.SaveAudio",
  "nodetool.audio.SaveAudioFile",
  "nodetool.audio.Normalize",
  "nodetool.audio.OverlayAudio",
  "nodetool.audio.RemoveSilence",
  "nodetool.audio.SliceAudio",
  "nodetool.audio.MonoToStereo",
  "nodetool.audio.StereoToMono",
  "nodetool.audio.Reverse",
  "nodetool.audio.FadeIn",
  "nodetool.audio.FadeOut",
  "nodetool.audio.Repeat",
  "nodetool.audio.AudioMixer",
  "nodetool.audio.AudioToNumpy",
  "nodetool.audio.NumpyToAudio",
  "nodetool.audio.Trim",
  "nodetool.audio.ConvertToArray",
  "nodetool.audio.CreateSilence",
  "nodetool.audio.Concat",
  "nodetool.audio.ConcatList",
  "nodetool.audio.TextToSpeech",
  "nodetool.audio.ChunkToAudio",
  "nodetool.code.ExecutePython",
  "nodetool.code.ExecuteJavaScript",
  "nodetool.code.ExecuteBash",
  "nodetool.code.ExecuteRuby",
  "nodetool.code.ExecuteLua",
  "nodetool.code.ExecuteCommand",
  "nodetool.code.RunPythonCommand",
  "nodetool.code.RunJavaScriptCommand",
  "nodetool.code.RunBashCommand",
  "nodetool.code.RunRubyCommand",
  "nodetool.code.RunLuaCommand",
  "nodetool.code.RunLuaCommandDocker",
  "nodetool.code.RunShellCommand",
  "nodetool.compare.CompareImages",
  "nodetool.data.Schema",
  "nodetool.data.Filter",
  "nodetool.data.Slice",
  "nodetool.data.SaveDataframe",
  "nodetool.data.ImportCSV",
  "nodetool.data.LoadCSVURL",
  "nodetool.data.LoadCSVFile",
  "nodetool.data.FromList",
  "nodetool.data.JSONToDataframe",
  "nodetool.data.ToList",
  "nodetool.data.SelectColumn",
  "nodetool.data.ExtractColumn",
  "nodetool.data.AddColumn",
  "nodetool.data.Merge",
  "nodetool.data.Append",
  "nodetool.data.Join",
  "nodetool.data.RowIterator",
  "nodetool.data.FindRow",
  "nodetool.data.SortByColumn",
  "nodetool.data.DropDuplicates",
  "nodetool.data.DropNA",
  "nodetool.data.ForEachRow",
  "nodetool.data.LoadCSVAssets",
  "nodetool.data.Aggregate",
  "nodetool.data.Pivot",
  "nodetool.data.Rename",
  "nodetool.data.FillNA",
  "nodetool.data.SaveCSVDataframeFile",
  "nodetool.data.FilterNone",
  "nodetool.document.LoadDocumentFile",
  "nodetool.document.SaveDocumentFile",
  "nodetool.document.ListDocuments",
  "nodetool.document.SplitDocument",
  "nodetool.document.SplitHTML",
  "nodetool.document.SplitJSON",
  "nodetool.document.SplitRecursively",
  "nodetool.document.SplitMarkdown",
  "nodetool.generators.StructuredOutputGenerator",
  "nodetool.generators.DataGenerator",
  "nodetool.generators.ListGenerator",
  "nodetool.generators.ChartGenerator",
  "nodetool.generators.SVGGenerator",
  "nodetool.image.LoadImageFile",
  "nodetool.image.LoadImageFolder",
  "nodetool.image.SaveImageFile",
  "nodetool.image.LoadImageAssets",
  "nodetool.image.SaveImage",
  "nodetool.image.GetMetadata",
  "nodetool.image.BatchToList",
  "nodetool.image.ImagesToList",
  "nodetool.image.Paste",
  "nodetool.image.Scale",
  "nodetool.image.Resize",
  "nodetool.image.Crop",
  "nodetool.image.Fit",
  "nodetool.image.TextToImage",
  "nodetool.image.ImageToImage",
  "nodetool.input.FloatInput",
  "nodetool.input.BooleanInput",
  "nodetool.input.IntegerInput",
  "nodetool.input.StringInput",
  "nodetool.input.SelectInput",
  "nodetool.input.StringListInput",
  "nodetool.input.FolderPathInput",
  "nodetool.input.HuggingFaceModelInput",
  "nodetool.input.ColorInput",
  "nodetool.input.ImageSizeInput",
  "nodetool.input.LanguageModelInput",
  "nodetool.input.ImageModelInput",
  "nodetool.input.VideoModelInput",
  "nodetool.input.TTSModelInput",
  "nodetool.input.ASRModelInput",
  "nodetool.input.EmbeddingModelInput",
  "nodetool.input.DataframeInput",
  "nodetool.input.DocumentInput",
  "nodetool.input.ImageInput",
  "nodetool.input.ImageListInput",
  "nodetool.input.VideoListInput",
  "nodetool.input.AudioListInput",
  "nodetool.input.TextListInput",
  "nodetool.input.VideoInput",
  "nodetool.input.AudioInput",
  "nodetool.input.Model3DInput",
  "nodetool.input.RealtimeAudioInput",
  "nodetool.input.AssetFolderInput",
  "nodetool.input.FilePathInput",
  "nodetool.input.DocumentFileInput",
  "nodetool.input.MessageInput",
  "nodetool.input.MessageListInput",
  "nodetool.input.MessageDeconstructor",
  "nodetool.model3d.LoadModel3DFile",
  "nodetool.model3d.SaveModel3DFile",
  "nodetool.model3d.SaveModel3D",
  "nodetool.model3d.FormatConverter",
  "nodetool.model3d.GetModel3DMetadata",
  "nodetool.model3d.Transform3D",
  "nodetool.model3d.Decimate",
  "nodetool.model3d.Boolean3D",
  "nodetool.model3d.RecalculateNormals",
  "nodetool.model3d.CenterMesh",
  "nodetool.model3d.FlipNormals",
  "nodetool.model3d.MergeMeshes",
  "nodetool.model3d.TextTo3D",
  "nodetool.model3d.ImageTo3D",
  "nodetool.output.Output",
  "nodetool.triggers.WaitNode",
  "nodetool.video.TextToVideo",
  "nodetool.video.ImageToVideo",
  "nodetool.video.LoadVideoFile",
  "nodetool.video.SaveVideoFile",
  "nodetool.video.LoadVideoAssets",
  "nodetool.video.SaveVideo",
  "nodetool.video.FrameIterator",
  "nodetool.video.Fps",
  "nodetool.video.FrameToVideo",
  "nodetool.video.Concat",
  "nodetool.video.Trim",
  "nodetool.video.ResizeNode",
  "nodetool.video.Rotate",
  "nodetool.video.SetSpeed",
  "nodetool.video.Overlay",
  "nodetool.video.ColorBalance",
  "nodetool.video.Denoise",
  "nodetool.video.Stabilize",
  "nodetool.video.Sharpness",
  "nodetool.video.Blur",
  "nodetool.video.Saturation",
  "nodetool.video.AddSubtitles",
  "nodetool.video.Reverse",
  "nodetool.video.Transition",
  "nodetool.video.AddAudio",
  "nodetool.video.ChromaKey",
  "nodetool.video.ExtractAudio",
  "nodetool.video.ExtractFrame",
  "nodetool.video.GetVideoInfo",
  "nodetool.workspace.GetWorkspaceDir",
  "nodetool.workspace.ListWorkspaceFiles",
  "nodetool.workspace.ReadTextFile",
  "nodetool.workspace.WriteTextFile",
  "nodetool.workspace.ReadBinaryFile",
  "nodetool.workspace.WriteBinaryFile",
  "nodetool.workspace.DeleteWorkspaceFile",
  "nodetool.workspace.CreateWorkspaceDirectory",
  "nodetool.workspace.WorkspaceFileExists",
  "nodetool.workspace.GetWorkspaceFileInfo",
  "nodetool.workspace.CopyWorkspaceFile",
  "nodetool.workspace.MoveWorkspaceFile",
  "nodetool.workspace.GetWorkspaceFileSize",
  "nodetool.workspace.IsWorkspaceFile",
  "nodetool.workspace.IsWorkspaceDirectory",
  "nodetool.workspace.JoinWorkspacePaths",
  "nodetool.workspace.SaveImageFile",
  "nodetool.workspace.SaveVideoFile",
] as const;

export const EXTENDED_PLACEHOLDER_NODES: NodeClass[] =
  EXTENDED_PLACEHOLDER_NODE_TYPES.map((nodeType) => makePlaceholderNode(nodeType));

