import type { NodeClass, NodeRegistry } from "@nodetool/node-sdk";

export {
  IfNode,
  ForEachNode,
  CollectNode,
  RerouteNode,
  CONTROL_NODES,
} from "./nodes/control.js";
export {
  ConditionalSwitchNode,
  LogicalOperatorNode,
  NotNode,
  CompareNode,
  IsNoneNode,
  IsInNode,
  AllNode,
  SomeNode,
  BOOLEAN_NODES,
} from "./nodes/boolean.js";
export {
  LengthNode,
  ListRangeNode,
  GenerateSequenceNode,
  SliceNode,
  SelectElementsNode,
  GetElementNode,
  AppendNode,
  ExtendNode,
  DedupeNode,
  ReverseNode,
  RandomizeNode,
  SortNode,
  IntersectionNode,
  UnionNode,
  DifferenceNode,
  ChunkNode,
  SumNode,
  AverageNode,
  MinimumNode,
  MaximumNode,
  ProductNode,
  FlattenNode,
  SaveListNode,
  LIST_NODES,
} from "./nodes/list.js";
export {
  ToStringNode,
  ConcatTextNode,
  JoinTextNode,
  ReplaceTextNode,
  CollectTextNode,
  FormatTextNode,
  TemplateTextNode,
  TEXT_NODES,
} from "./nodes/text.js";
export {
  SplitTextNode,
  ExtractTextNode,
  ChunkTextNode,
  ExtractRegexNode,
  FindAllRegexNode,
  TextParseJSONNode,
  ExtractJSONNode,
  RegexMatchNode,
  RegexReplaceNode,
  RegexSplitNode,
  RegexValidateNode,
  CompareTextNode,
  EqualsTextNode,
  ToUppercaseNode,
  ToLowercaseNode,
  ToTitlecaseNode,
  CapitalizeTextNode,
  SliceTextNode,
  StartsWithTextNode,
  EndsWithTextNode,
  ContainsTextNode,
  TrimWhitespaceNode,
  CollapseWhitespaceNode,
  IsEmptyTextNode,
  RemovePunctuationNode,
  StripAccentsNode,
  SlugifyNode,
  HasLengthTextNode,
  TruncateTextNode,
  PadTextNode,
  LengthTextNode,
  IndexOfTextNode,
  SurroundWithTextNode,
  CountTokensNode,
  HtmlToTextNode,
  AutomaticSpeechRecognitionNode,
  EmbeddingTextNode,
  SaveTextFileNode,
  SaveTextNode,
  LoadTextFolderNode,
  LoadTextAssetsNode,
  FilterStringNode,
  FilterRegexStringNode,
  TEXT_EXTRA_NODES,
} from "./nodes/text-extra.js";
export {
  ConstantBaseNode,
  ConstantBoolNode,
  ConstantIntegerNode,
  ConstantFloatNode,
  ConstantStringNode,
  ConstantListNode,
  ConstantTextListNode,
  ConstantDictNode,
  ConstantAudioNode,
  ConstantImageNode,
  ConstantVideoNode,
  ConstantDocumentNode,
  ConstantJSONNode,
  ConstantModel3DNode,
  ConstantDataFrameNode,
  ConstantAudioListNode,
  ConstantImageListNode,
  ConstantVideoListNode,
  ConstantSelectNode,
  ConstantImageSizeNode,
  ConstantDateNode,
  ConstantDateTimeNode,
  ConstantASRModelNode,
  ConstantEmbeddingModelNode,
  ConstantImageModelNode,
  ConstantLanguageModelNode,
  ConstantTTSModelNode,
  ConstantVideoModelNode,
  CONSTANT_NODES,
} from "./nodes/constant.js";
export {
  FilterNumberNode,
  FilterNumberRangeNode,
  NUMBERS_NODES,
} from "./nodes/numbers.js";
export {
  GetValueNode,
  UpdateDictionaryNode,
  RemoveDictionaryKeyNode,
  ParseJSONNode,
  ZipDictionaryNode,
  CombineDictionaryNode,
  FilterDictionaryNode,
  ReduceDictionariesNode,
  MakeDictionaryNode,
  ArgMaxNode,
  ToJSONNode,
  ToYAMLNode,
  LoadCSVFileNode,
  SaveCSVFileNode,
  FilterDictByQueryNode,
  FilterDictByNumberNode,
  FilterDictByRangeNode,
  FilterDictRegexNode,
  FilterDictByValueNode,
  DICTIONARY_NODES,
} from "./nodes/dictionary.js";
export {
  FloatInputNode,
  BooleanInputNode,
  IntegerInputNode,
  StringInputNode,
  SelectInputNode,
  StringListInputNode,
  FolderPathInputNode,
  HuggingFaceModelInputNode,
  ColorInputNode,
  ImageSizeInputNode,
  LanguageModelInputNode,
  ImageModelInputNode,
  VideoModelInputNode,
  TTSModelInputNode,
  ASRModelInputNode,
  EmbeddingModelInputNode,
  DataframeInputNode,
  DocumentInputNode,
  ImageInputNode,
  ImageListInputNode,
  VideoListInputNode,
  AudioListInputNode,
  TextListInputNode,
  VideoInputNode,
  AudioInputNode,
  Model3DInputNode,
  RealtimeAudioInputNode,
  AssetFolderInputNode,
  FilePathInputNode,
  DocumentFileInputNode,
  MessageInputNode,
  MessageListInputNode,
  MessageDeconstructorNode,
  INPUT_NODES,
} from "./nodes/input.js";
export { OutputNode, PreviewNode, OUTPUT_NODES } from "./nodes/output.js";
export {
  GetWorkspaceDirNode,
  ListWorkspaceFilesNode,
  ReadTextFileNode,
  WriteTextFileNode,
  ReadBinaryFileNode,
  WriteBinaryFileNode,
  DeleteWorkspaceFileNode,
  CreateWorkspaceDirectoryNode,
  WorkspaceFileExistsNode,
  GetWorkspaceFileInfoNode,
  CopyWorkspaceFileNode,
  MoveWorkspaceFileNode,
  GetWorkspaceFileSizeNode,
  IsWorkspaceFileNode,
  IsWorkspaceDirectoryNode,
  JoinWorkspacePathsNode,
  SaveImageFileNode,
  SaveVideoFileNode,
  WORKSPACE_NODES,
} from "./nodes/workspace.js";
export { CompareImagesNode, COMPARE_NODES } from "./nodes/compare.js";
export {
  LoadDocumentFileNode,
  SaveDocumentFileNode,
  ListDocumentsNode,
  SplitDocumentNode,
  SplitHTMLNode,
  SplitJSONNode,
  SplitRecursivelyNode,
  SplitMarkdownNode,
  DOCUMENT_NODES,
} from "./nodes/document.js";
export {
  SchemaNode,
  FilterDataframeNode,
  SliceDataframeNode,
  SaveDataframeNode,
  ImportCSVNode,
  LoadCSVURLNode,
  LoadCSVFileDataNode,
  FromListNode,
  JSONToDataframeNode,
  ToListNode,
  SelectColumnNode,
  ExtractColumnNode,
  AddColumnNode,
  MergeDataframeNode,
  AppendDataframeNode,
  JoinDataframeNode,
  RowIteratorNode,
  FindRowNode,
  SortByColumnNode,
  DropDuplicatesNode,
  DropNANode,
  ForEachRowNode,
  LoadCSVAssetsNode,
  AggregateNode,
  PivotNode,
  RenameNode,
  FillNANode,
  SaveCSVDataframeFileNode,
  FilterNoneNode,
  DATA_NODES,
} from "./nodes/data.js";
export {
  ExecutePythonNode,
  ExecuteJavaScriptNode,
  ExecuteBashNode,
  ExecuteRubyNode,
  ExecuteLuaNode,
  ExecuteCommandNode,
  RunPythonCommandNode,
  RunJavaScriptCommandNode,
  RunBashCommandNode,
  RunRubyCommandNode,
  RunLuaCommandNode,
  RunLuaCommandDockerNode,
  RunShellCommandNode,
  RunPythonCommandDockerNode,
  RunJavaScriptCommandDockerNode,
  RunBashCommandDockerNode,
  RunRubyCommandDockerNode,
  RunShellCommandDockerNode,
  CODE_NODES,
} from "./nodes/code.js";
export {
  LoadAudioAssetsNode,
  LoadAudioFileNode,
  LoadAudioFolderNode,
  SaveAudioNode,
  SaveAudioFileNode,
  NormalizeAudioNode,
  OverlayAudioNode,
  RemoveSilenceNode,
  SliceAudioNode,
  MonoToStereoNode,
  StereoToMonoNode,
  ReverseAudioNode,
  FadeInAudioNode,
  FadeOutAudioNode,
  RepeatAudioNode,
  AudioMixerNode,
  AudioToNumpyNode,
  NumpyToAudioNode,
  TrimAudioNode,
  ConvertToArrayNode,
  CreateSilenceNode,
  ConcatAudioNode,
  ConcatAudioListNode,
  TextToSpeechNode,
  ChunkToAudioNode,
  AUDIO_NODES,
} from "./nodes/audio.js";
export {
  WaitNode,
  WaitAliasNode,
  ManualTriggerNode,
  IntervalTriggerNode,
  WebhookTriggerNode,
  FileWatchTriggerNode,
  TRIGGER_NODES,
} from "./nodes/triggers.js";
export {
  LoadImageFileNode,
  LoadImageFolderNode,
  SaveImageFileImageNode,
  LoadImageAssetsNode,
  SaveImageNode,
  GetMetadataNode,
  BatchToListNode,
  ImagesToListNode,
  PasteNode,
  ScaleNode,
  ResizeNode,
  CropNode,
  FitNode,
  TextToImageNode,
  ImageToImageNode,
  IMAGE_NODES,
} from "./nodes/image.js";
export {
  TextToVideoNode,
  ImageToVideoNode,
  LoadVideoFileNode,
  SaveVideoFileVideoNode,
  LoadVideoAssetsNode,
  SaveVideoNode,
  FrameIteratorNode,
  FpsNode,
  FrameToVideoNode,
  ConcatVideoNode,
  TrimVideoNode,
  ResizeVideoNode,
  ResizeVideoAliasNode,
  RotateVideoNode,
  SetSpeedVideoNode,
  OverlayVideoNode,
  ColorBalanceVideoNode,
  DenoiseVideoNode,
  StabilizeVideoNode,
  SharpnessVideoNode,
  BlurVideoNode,
  SaturationVideoNode,
  AddSubtitlesVideoNode,
  ReverseVideoNode,
  TransitionVideoNode,
  AddAudioVideoNode,
  ChromaKeyVideoNode,
  ExtractAudioVideoNode,
  ExtractFrameVideoNode,
  GetVideoInfoNode,
  VIDEO_NODES,
} from "./nodes/video.js";
export {
  SummarizerNode,
  CreateThreadNode,
  ExtractorNode,
  ClassifierNode,
  AgentNode,
  ControlAgentNode,
  ResearchAgentNode,
  AGENT_NODES,
} from "./nodes/agents.js";
export {
  StructuredOutputGeneratorNode,
  DataGeneratorNode,
  ListGeneratorNode,
  ChartGeneratorNode,
  SVGGeneratorNode,
  GENERATOR_NODES,
} from "./nodes/generators.js";
export {
  LoadModel3DFileNode,
  SaveModel3DFileNode,
  SaveModel3DNode,
  FormatConverterNode,
  GetModel3DMetadataNode,
  Transform3DNode,
  DecimateNode,
  Boolean3DNode,
  RecalculateNormalsNode,
  CenterMeshNode,
  FlipNormalsNode,
  MergeMeshesNode,
  TextTo3DNode,
  ImageTo3DNode,
  MODEL3D_NODES,
} from "./nodes/model3d.js";
export {
  GenerateUUID4Node,
  GenerateUUID1Node,
  GenerateUUID3Node,
  GenerateUUID5Node,
  ParseUUIDNode,
  FormatUUIDNode,
  IsValidUUIDNode,
  UUID_NODES,
} from "./nodes/uuid.js";
export { LIB_COMPAT_PY_NODES } from "./nodes/lib-compat.js";
export {
  AddLibNode,
  SubtractLibNode,
  MultiplyLibNode,
  DivideLibNode,
  ModulusLibNode,
  MathFunctionLibNode,
  SineLibNode,
  CosineLibNode,
  PowerLibNode,
  SqrtLibNode,
  LIB_MATH_NODES,
} from "./nodes/lib-math.js";
export {
  ParseDictLibNode,
  ParseListLibNode,
  StringifyJSONLibNode,
  GetJSONPathStrLibNode,
  GetJSONPathIntLibNode,
  GetJSONPathFloatLibNode,
  GetJSONPathBoolLibNode,
  GetJSONPathListLibNode,
  GetJSONPathDictLibNode,
  ValidateJSONLibNode,
  FilterJSONLibNode,
  JSONTemplateLibNode,
  LoadJSONAssetsLibNode,
  LIB_JSON_NODES,
} from "./nodes/lib-json.js";
export {
  TodayLibNode,
  NowLibNode,
  ParseDateLibNode,
  ParseDateTimeLibNode,
  AddTimeDeltaLibNode,
  DateDifferenceLibNode,
  FormatDateTimeLibNode,
  GetWeekdayLibNode,
  DateRangeLibNode,
  IsDateInRangeLibNode,
  GetQuarterLibNode,
  DateToDatetimeLibNode,
  DatetimeToDateLibNode,
  RelativeTimeLibNode,
  BoundaryTimeLibNode,
  LIB_DATE_NODES,
} from "./nodes/lib-date.js";
export {
  WorkspaceDirectoryLibNode,
  OpenWorkspaceDirectoryLibNode,
  FileExistsLibNode,
  ListFilesLibNode,
  CopyFileLibNode,
  MoveFileLibNode,
  CreateDirectoryLibNode,
  GetFileSizeLibNode,
  CreatedTimeLibNode,
  ModifiedTimeLibNode,
  AccessedTimeLibNode,
  IsFileLibNode,
  IsDirectoryLibNode,
  FileExtensionLibNode,
  FileNameLibNode,
  GetDirectoryLibNode,
  FileNameMatchLibNode,
  FilterFileNamesLibNode,
  BasenameLibNode,
  DirnameLibNode,
  JoinPathsLibNode,
  NormalizePathLibNode,
  GetPathInfoLibNode,
  AbsolutePathLibNode,
  SplitPathLibNode,
  SplitExtensionLibNode,
  RelativePathLibNode,
  PathToStringLibNode,
  ShowNotificationLibNode,
  LIB_OS_NODES,
} from "./nodes/lib-os.js";
export {
  ExtractLinksMarkdownLibNode,
  ExtractHeadersMarkdownLibNode,
  ExtractBulletListsMarkdownLibNode,
  ExtractNumberedListsMarkdownLibNode,
  ExtractCodeBlocksMarkdownLibNode,
  ExtractTablesMarkdownLibNode,
  LIB_MARKDOWN_NODES,
} from "./nodes/lib-markdown.js";
export { GetSecretLibNode, LIB_SECRET_NODES } from "./nodes/lib-secret.js";
export {
  GetRequestLibNode,
  PostRequestLibNode,
  PutRequestLibNode,
  DeleteRequestLibNode,
  HeadRequestLibNode,
  FetchPageLibNode,
  ImageDownloaderLibNode,
  GetRequestBinaryLibNode,
  GetRequestDocumentLibNode,
  PostRequestBinaryLibNode,
  DownloadDataframeLibNode,
  FilterValidURLsLibNode,
  DownloadFilesLibNode,
  JSONPostRequestLibNode,
  JSONPutRequestLibNode,
  JSONPatchRequestLibNode,
  JSONGetRequestLibNode,
  LIB_HTTP_NODES,
} from "./nodes/lib-http.js";
export {
  ConvertFilePandocLibNode,
  ConvertTextPandocLibNode,
  LIB_PANDOC_NODES,
} from "./nodes/lib-pandoc.js";
export { YtDlpDownloadLibNode, LIB_YTDLP_NODES } from "./nodes/lib-ytdlp.js";
export {
  SliceImageGridLibNode,
  CombineImageGridLibNode,
  LIB_GRID_NODES,
} from "./nodes/lib-grid.js";
export {
  RectLibNode,
  CircleLibNode,
  EllipseLibNode,
  LineLibNode,
  PolygonLibNode,
  PathLibNode,
  TextLibNode,
  GaussianBlurLibNode,
  DropShadowLibNode,
  DocumentLibNode,
  SVGToImageLibNode,
  GradientLibNode,
  TransformLibNode,
  ClipPathLibNode,
  LIB_SVG_NODES,
} from "./nodes/lib-svg.js";
export { LIB_PILLOW_NODES } from "./nodes/lib-pillow.js";
export {
  FetchRSSFeedLibNode,
  ExtractFeedMetadataLibNode,
  LIB_RSS_NODES,
} from "./nodes/lib-rss.js";

import { CONTROL_NODES } from "./nodes/control.js";
import { BOOLEAN_NODES } from "./nodes/boolean.js";
import { LIST_NODES } from "./nodes/list.js";
import { TEXT_NODES } from "./nodes/text.js";
import { TEXT_EXTRA_NODES } from "./nodes/text-extra.js";
import { CONSTANT_NODES } from "./nodes/constant.js";
import { NUMBERS_NODES } from "./nodes/numbers.js";
import { DICTIONARY_NODES } from "./nodes/dictionary.js";
import { EXTENDED_PLACEHOLDER_NODES } from "./nodes/extended-placeholders.js";
import { INPUT_NODES } from "./nodes/input.js";
import { OUTPUT_NODES } from "./nodes/output.js";
import { WORKSPACE_NODES } from "./nodes/workspace.js";
import { COMPARE_NODES } from "./nodes/compare.js";
import { DOCUMENT_NODES } from "./nodes/document.js";
import { DATA_NODES } from "./nodes/data.js";
import { CODE_NODES } from "./nodes/code.js";
import { AUDIO_NODES } from "./nodes/audio.js";
import { TRIGGER_NODES } from "./nodes/triggers.js";
import { IMAGE_NODES } from "./nodes/image.js";
import { VIDEO_NODES } from "./nodes/video.js";
import { AGENT_NODES } from "./nodes/agents.js";
import { GENERATOR_NODES } from "./nodes/generators.js";
import { MODEL3D_NODES } from "./nodes/model3d.js";
import { UUID_NODES } from "./nodes/uuid.js";
import { LIB_COMPAT_PY_NODES } from "./nodes/lib-compat.js";
import { LIB_MATH_NODES } from "./nodes/lib-math.js";
import { LIB_JSON_NODES } from "./nodes/lib-json.js";
import { LIB_DATE_NODES } from "./nodes/lib-date.js";
import { LIB_OS_NODES } from "./nodes/lib-os.js";
import { LIB_MARKDOWN_NODES } from "./nodes/lib-markdown.js";
import { LIB_SECRET_NODES } from "./nodes/lib-secret.js";
import { LIB_HTTP_NODES } from "./nodes/lib-http.js";
import { LIB_PANDOC_NODES } from "./nodes/lib-pandoc.js";
import { LIB_YTDLP_NODES } from "./nodes/lib-ytdlp.js";
import { LIB_GRID_NODES } from "./nodes/lib-grid.js";
import { LIB_SVG_NODES } from "./nodes/lib-svg.js";
import { LIB_PILLOW_NODES } from "./nodes/lib-pillow.js";
import { LIB_RSS_NODES } from "./nodes/lib-rss.js";

export const ALL_BASE_NODES: readonly NodeClass[] = [
  ...CONTROL_NODES,
  ...BOOLEAN_NODES,
  ...LIST_NODES,
  ...TEXT_NODES,
  ...TEXT_EXTRA_NODES,
  ...CONSTANT_NODES,
  ...NUMBERS_NODES,
  ...DICTIONARY_NODES,
  ...EXTENDED_PLACEHOLDER_NODES,
  ...INPUT_NODES,
  ...OUTPUT_NODES,
  ...WORKSPACE_NODES,
  ...COMPARE_NODES,
  ...DOCUMENT_NODES,
  ...DATA_NODES,
  ...CODE_NODES,
  ...AUDIO_NODES,
  ...TRIGGER_NODES,
  ...IMAGE_NODES,
  ...VIDEO_NODES,
  ...AGENT_NODES,
  ...GENERATOR_NODES,
  ...MODEL3D_NODES,
  ...UUID_NODES,
  ...LIB_COMPAT_PY_NODES,
  ...LIB_MATH_NODES,
  ...LIB_JSON_NODES,
  ...LIB_DATE_NODES,
  ...LIB_OS_NODES,
  ...LIB_MARKDOWN_NODES,
  ...LIB_SECRET_NODES,
  ...LIB_HTTP_NODES,
  ...LIB_PANDOC_NODES,
  ...LIB_YTDLP_NODES,
  ...LIB_GRID_NODES,
  ...LIB_SVG_NODES,
  ...LIB_PILLOW_NODES,
  ...LIB_RSS_NODES,
];

export function registerBaseNodes(registry: NodeRegistry): void {
  for (const nodeClass of ALL_BASE_NODES) {
    if (nodeClass.nodeType === "nodetool.workflows.base_node.Preview") {
      registry.register(nodeClass, {
        metadata: {
          title: "Preview",
          description: "Preview values inside the workflow graph",
          namespace: "nodetool.workflows.base_node",
          node_type: "nodetool.workflows.base_node.Preview",
          properties: [
            { name: "value", type: { type: "any" }, default: null },
            { name: "name", type: { type: "str" }, default: "" },
          ],
          outputs: [{ name: "output", type: { type: "any" } }],
          basic_fields: ["value"],
        },
      });
      continue;
    }
    registry.register(nodeClass);
  }
}
